f:=e^(-x)*sin (x);
int (f, x);
int (f, x, 0, infinity);
int (f, x, 0, b);
sin (b)+cos (b);
c:=sin (b)+cos (b);
limit (c, b,infinity);
limit ((2*x+5)/(3*x-2), x, infinity);
int (e^(-x)*sin (x), x, 0, infinity);
end;
